# TODO: Translation updated at 2026-06-02 13:12

translate french strings:

    # game/options.rpy:15
    old "Come Home"
    new "Come Home"

    # game/options.rpy:35
    old "1.01\n\nReleased (2026-04-24)\n\n- Changed Brandichat from images to screens.\n\n- Changed Polaroid menus to be built in-game instead of pre-made images.\n\n- Improved menu functions to prevent weird rollback issues.\n\n- Made Suzy and Lisa's relationship words more specific - you now specify what the relationship is and how you refer to them as separate things.\n\n- Changed some phone menus to image menus.\n\n- Added sex menus to some characters repeatable sex screens.\n\n- Added four new scenes based off Patreon/Subscribestar polls:\n\n- Added Lisa TV Doggystyle scene\n\n- Added Izzy Anal Missionary scene\n\n- Added Reba Anal Cowgirl scene\n\n- Added Mi-Cha Facefuck Punishment scene\n\n- Fixed some images in the scene where you first have sex with Jez.\n\n- Added 16 new possible combinations for the harem orgy scene.\n\n- Added Chinese and Spanish translations.\n\n- Made it so the \"Telling Suzy\" scene in Lisa's end-game gallery shows up whether you've completed it or not.\n\n- Fixed a bug that would cause Mari's anal scene to play even if you rejected it.\n\n- Various bug fixes.\n\n\n\n\n\n"
    new "1.01\n\nSortie (24/04/2026)\n\n- Le chat de Brandi est maintenant composé d'écrans plutôt que d'images.\n\n- Modification des menus Polaroid pour qu'ils soient intégrés au jeu au lieu d'utiliser des images prédéfinies.\n\n- Amélioration des fonctions du menu pour éviter d'étranges problèmes de rollback.\n\n- Les termes des relations à Suzy et Lisa sont plus spécifiques : vous pouvez désormais spécifier la nature de la relation et la manière dont vous vous y référez comme des éléments distincts.\n\n- Remplacement de certains menus téléphoniques par des menus d'images.\n\n- Ajout de menus sexuels aux scènes de sexe répétables de certains personnages.\n\n- Ajout de quatre nouvelles scènes basées sur les sondages Patreon/Subscribestar :\n\n- Ajout d'une scène avec Lisa en levrette devant la télé\n\n- Ajout d'une scène de missionaire anal avec Izzy\n\n- Ajout d'une scène de cowgirl en anal avec Reba\n\n- Ajout d'une scène de punition "à l'oral" pour Mi-Cha\n\n- Correction de certaines images dans la scène du premier rapport sexuel avec Jez.\n\n- Ajout de 16 nouvelles combinaisons possibles pour la scène d'orgie du harem.\n\n- Ajout des traductions en chinois et en espagnol.\n\n- La scène d'aveu à Suzy apparaît dans la galerie de fin de jeu de Lisa, que vous l'ayez terminée ou non.\n\n- Correction d'un bug qui provoquait la lecture de la scène anale de Mari même si vous l'aviez refusée.\n\n- Diverses corrections de bugs.\n\n\n\n\n\n"

